### ISSUE TITLE
 The label info is from the image file name?

### ISSUE THREAD

**Issue by bemoregt** [jacobgil/pytorch-explain-black-box#2]
HI, @jacobgil @jacobsagivtech 

I run your code successfully.

But, Where is the label information?

The label info is from the image file name?

Thanks.

**Comment by jacobgil** [comment]
The target class is obtained by doing a forward pass, and finding the class that got the highest score.
https://github.com/jacobgil/pytorch-explain-black-box/blob/master/explain.py#L115
