### ISSUE TITLE
Missing reference for operation in the code

### ISSUE THREAD

**Issue by godimarcovr** [jacobgil/pytorch-explain-black-box#3]
Hi, thank you for your work!
Playing with the code i noticed that adding noise has a lot of impact on the result and i was wondering if you could add the reference for this technique in the description.
"Also now gaussian noise with a sigma of 0.2 is added to the preprocssed image at each iteration, inspired by google's SmoothGradient." i found only this in your description, but the name is too generic to find what you were referring to.
Could you point me to the paper/article? Thanks!

**Comment by jacobgil** [comment]
https://arxiv.org/abs/1706.03825
https://pair-code.github.io/saliency/
