### ISSUE TITLE
Interpretation of the Heatmap

### ISSUE THREAD

**Issue by bnaman50** [jacobgil/pytorch-explain-black-box#7]
Hey Jacob, 

Thanks for this great and easy to use implementation of meaningful perturbation algorithm. 

I just have a small question. Could you please help me understand the interpretation of the heatmap. As per my understanding, the heatmap is the same thing as the mask (values between 0 and 1) representing the minimum region in the image that you would suppress to reduce the prediction score maximally. 

My understanding that the mask is same as the heatmap is based on the following lines from your code: 
```
mask = 1 - mask
heatmap = cv2.applyColorMap(np.uint8(255*mask), cv2.COLORMAP_JET)
heatmap = np.float32(heatmap) / 255
```
Could you please confirm whether my understanding is correct or is it something else?

Thanks, 
Naman

**Comment by jacobgil** [comment]
Hi, yes this is correct.
